FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential cmake \
    libgl1 libglib2.0-0 \
    libsm6 libxext6 libxrender-dev \
    libgtk2.0-dev libboost-all-dev \
    tesseract-ocr \
    netcat-openbsd \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY wait-for-db.sh .
RUN chmod +x wait-for-db.sh

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
