FROM python:3.11-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential cmake \
    libgl1 libglib2.0-0 \
    libsm6 libxext6 libxrender-dev \
    libgtk2.0-dev \
    tesseract-ocr \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip wheel setuptools && \
    pip wheel --wheel-dir=/wheels -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 libglib2.0-0 \
    libsm6 libxext6 libxrender-dev \
    libgtk2.0-dev \
    tesseract-ocr \
    netcat-openbsd \
 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /wheels /wheels
COPY requirements.txt .

RUN pip install --no-cache-dir --no-index --find-links=/wheels -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
